--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: jenkins
  name: hello-jen-svc
spec: 
  ports: 
    - 
      port: 8080
      protocol: TCP
  selector: 
    app: jenkins
  type: LoadBalancer
